table _Measures
	lineageTag: be606ed4-f0a4-44a0-9c2c-e3f3ab775902

	column Value
		isHidden
		lineageTag: 91d9cc1b-d1b9-4c06-9ed1-3976f6f86d6f
		isNameInferred
		sourceColumn: [Value]

	/// Career games played (additive).
	measure 'Total Games' =
			SUM(baseball_hits[G])
		formatString: #,0
		displayFolder: 01 Counting
		lineageTag: dbe021b5-bdd1-480a-ae20-897f9c0b7162

	/// At-bats — the denominator for most rate stats.
	measure 'Total At-Bats' =
			SUM(baseball_hits[AB])
		formatString: #,0
		displayFolder: 01 Counting
		lineageTag: 2562c252-97d4-41dd-ae64-285f165007bb

	/// Runs scored.
	measure 'Total Runs' =
			SUM(baseball_hits[R])
		formatString: #,0
		displayFolder: 01 Counting
		lineageTag: 48c8b7bb-c4c1-45ed-8ade-3ea05990f6cf

	/// Career hits.
	measure 'Total Hits' =
			SUM(baseball_hits[H])
		formatString: #,0
		displayFolder: 01 Counting
		lineageTag: 8a6f46df-a33d-41a0-8097-1d5364888bb6

	/// Doubles.
	measure 'Total Doubles' =
			SUM(baseball_hits[2B])
		formatString: #,0
		displayFolder: 01 Counting
		lineageTag: 4ce8c05e-397e-4b7b-b94e-7244c69ce65a

	/// Triples.
	measure 'Total Triples' =
			SUM(baseball_hits[3B])
		formatString: #,0
		displayFolder: 01 Counting
		lineageTag: 180a8952-24e6-445e-98d6-61d219e7c532

	/// Home runs.
	measure 'Total Home Runs' =
			SUM(baseball_hits[HR])
		formatString: #,0
		displayFolder: 01 Counting
		lineageTag: d70b1bbf-8fc0-458c-937e-b463dc69679e

	/// Runs batted in.
	measure 'Total RBI' =
			SUM(baseball_hits[RBI])
		formatString: #,0
		displayFolder: 01 Counting
		lineageTag: dd757b36-2f24-40e1-86ac-f69bfb39cc03

	/// Bases on balls (walks).
	measure 'Total Walks' =
			SUM(baseball_hits[BB])
		formatString: #,0
		displayFolder: 01 Counting
		lineageTag: b5e10be5-ad02-4f7e-b46f-3f171d7a9fec

	/// Strikeouts.
	measure 'Total Strikeouts' =
			SUM(baseball_hits[SO])
		formatString: #,0
		displayFolder: 01 Counting
		lineageTag: 24c8eb0e-8068-42aa-81f6-313142a4adfe

	/// Stolen bases.
	measure 'Total Stolen Bases' =
			SUM(baseball_hits[SB])
		formatString: #,0
		displayFolder: 01 Counting
		lineageTag: e37450ae-51b0-437c-8c17-53902ae91050

	/// Times caught stealing.
	measure 'Total Caught Stealing' =
			SUM(baseball_hits[CS])
		formatString: #,0
		displayFolder: 01 Counting
		lineageTag: 2133620b-05a8-4dfb-a463-d06de33b1a51

	/// Seasons played (player-seasons across a group).
	measure 'Total Seasons' =
			SUM(baseball_hits[YRS])
		formatString: #,0
		displayFolder: 01 Counting
		lineageTag: 3a3f86b1-9535-45cd-9751-989e2aaea06f

	/// Distinct players in context.
	measure 'Total Players' =
			DISTINCTCOUNT(baseball_hits[PLAYER])
		formatString: #,0
		displayFolder: 01 Counting
		lineageTag: b43f400c-cedf-47e0-80da-9421de70e897

	/// Approx plate appearances = AB + BB (no HBP/SF/SH in source).
	measure 'Total Plate Appearances' =
			SUM(baseball_hits[AB]) + SUM(baseball_hits[BB])
		formatString: #,0
		displayFolder: 01 Counting
		lineageTag: 9f8eeae6-b432-48d7-a74a-167289deacaf

	/// Hits / at-bats, aggregated SUM/SUM so it is correct at any grain.
	measure 'Batting Average' =
			DIVIDE(SUM(baseball_hits[H]), SUM(baseball_hits[AB]))
		formatString: 0.000
		displayFolder: 02 Rate Stats
		lineageTag: c85c304f-2337-49e3-9ee0-1595aa2f0973

	/// Approx OBP = (H+BB)/(AB+BB). No HBP/SF in source, so slightly below official OBP.
	measure 'On-Base Pct (approx)' =
			DIVIDE(SUM(baseball_hits[H]) + SUM(baseball_hits[BB]), SUM(baseball_hits[AB]) + SUM(baseball_hits[BB]))
		formatString: 0.000
		displayFolder: 02 Rate Stats
		lineageTag: 3fddcede-9cd1-4317-be10-2c50f78ac960

	/// Total bases / at-bats; singles derived as H-2B-3B-HR.
	measure 'Slugging Pct' =
			DIVIDE(
			    ( SUM(baseball_hits[H]) - SUM(baseball_hits[2B]) - SUM(baseball_hits[3B]) - SUM(baseball_hits[HR]) )
			        + 2 * SUM(baseball_hits[2B]) + 3 * SUM(baseball_hits[3B]) + 4 * SUM(baseball_hits[HR]),
			    SUM(baseball_hits[AB])
			)
		formatString: 0.000
		displayFolder: 02 Rate Stats
		lineageTag: 8b6cde0c-f73a-4ec8-8d73-1901008acbe8

	/// On-base plus slugging. Inherits the OBP approximation.
	measure 'OPS (approx)' =
			[On-Base Pct (approx)] + [Slugging Pct]
		formatString: 0.000
		displayFolder: 02 Rate Stats
		lineageTag: 2c00e4ce-dbd2-4acd-bf76-002383e88f6b

	/// Extra-base productivity = SLG - BA on aggregates.
	measure 'Isolated Power (ISO)' =
			[Slugging Pct] - [Batting Average]
		formatString: 0.000
		displayFolder: 02 Rate Stats
		lineageTag: 568690b6-0569-4875-9acb-c45d684e580d

	/// 1B + 2*2B + 3*3B + 4*HR.
	measure 'Total Bases' =
			( SUM(baseball_hits[H]) - SUM(baseball_hits[2B]) - SUM(baseball_hits[3B]) - SUM(baseball_hits[HR]) )
			    + 2 * SUM(baseball_hits[2B]) + 3 * SUM(baseball_hits[3B]) + 4 * SUM(baseball_hits[HR])
		formatString: #,0
		displayFolder: 03 Power
		lineageTag: fada4d97-0727-47aa-99eb-8c89cb243b7f

	/// Hits minus extra-base hits.
	measure 'Singles' =
			SUM(baseball_hits[H]) - SUM(baseball_hits[2B]) - SUM(baseball_hits[3B]) - SUM(baseball_hits[HR])
		formatString: #,0
		displayFolder: 03 Power
		lineageTag: 8f653235-001e-4530-9e76-04bc24ad655a

	/// Doubles + triples + home runs.
	measure 'Extra-Base Hits' =
			SUM(baseball_hits[2B]) + SUM(baseball_hits[3B]) + SUM(baseball_hits[HR])
		formatString: #,0
		displayFolder: 03 Power
		lineageTag: 166c1882-b80f-4a08-8462-e97b7e92a04c

	/// At-bats per home run; lower = more power.
	measure 'AB per HR' =
			DIVIDE(SUM(baseball_hits[AB]), SUM(baseball_hits[HR]))
		formatString: 0.0
		displayFolder: 03 Power
		lineageTag: 76778558-8725-45ac-bde2-2381a93af71e

	/// Home-run rate scaled to a full season.
	measure 'HR per 162 Games' =
			DIVIDE(SUM(baseball_hits[HR]), SUM(baseball_hits[G])) * 162
		formatString: 0.0
		displayFolder: 03 Power
		lineageTag: f609a5e4-4200-4628-9218-ec2df671560e

	/// Share of hits going for extra bases.
	measure 'XBH Pct of Hits' =
			DIVIDE([Extra-Base Hits], SUM(baseball_hits[H]))
		formatString: 0.0%
		displayFolder: 03 Power
		lineageTag: 53b06565-8fdc-4b03-971f-1b5f89a9fae5

	/// Share of hits that are home runs.
	measure 'HR Pct of Hits' =
			DIVIDE(SUM(baseball_hits[HR]), SUM(baseball_hits[H]))
		formatString: 0.0%
		displayFolder: 03 Power
		lineageTag: 4d64e3a4-cc6c-444c-b45e-3debbcf08365

	/// Walk-to-strikeout ratio; higher = better plate discipline.
	measure 'BB per K' =
			DIVIDE(SUM(baseball_hits[BB]), SUM(baseball_hits[SO]))
		formatString: 0.00
		displayFolder: 04 Discipline
		lineageTag: e5280ad6-835f-46ef-a077-9f3526669cbf

	/// Strikeouts per approx plate appearance.
	measure 'Strikeout Pct (approx)' =
			DIVIDE(SUM(baseball_hits[SO]), SUM(baseball_hits[AB]) + SUM(baseball_hits[BB]))
		formatString: 0.0%
		displayFolder: 04 Discipline
		lineageTag: 43998e10-3a06-4702-993f-d25ff690e9cd

	/// Walks per approx plate appearance.
	measure 'Walk Pct (approx)' =
			DIVIDE(SUM(baseball_hits[BB]), SUM(baseball_hits[AB]) + SUM(baseball_hits[BB]))
		formatString: 0.0%
		displayFolder: 04 Discipline
		lineageTag: b6242ac1-b27d-4906-a84e-176de8d1d7ca

	/// Stolen-base success = SB / (SB + CS).
	measure 'SB Success Pct' =
			DIVIDE(SUM(baseball_hits[SB]), SUM(baseball_hits[SB]) + SUM(baseball_hits[CS]))
		formatString: 0.0%
		displayFolder: 05 Speed
		lineageTag: d05525a8-8dd9-4528-9a6f-2fe558b442d3

	/// Total SB attempts.
	measure 'Stolen Base Attempts' =
			SUM(baseball_hits[SB]) + SUM(baseball_hits[CS])
		formatString: #,0
		displayFolder: 05 Speed
		lineageTag: dfd6f625-fadb-4084-8249-7cc246d1eccd

	/// Bill James Power-Speed Number = (2*HR*SB)/(HR+SB).
	measure 'Power-Speed Number' =
			VAR HRs = SUM(baseball_hits[HR])
			VAR SBs = SUM(baseball_hits[SB])
			RETURN DIVIDE(2 * HRs * SBs, HRs + SBs)
		formatString: 0.0
		displayFolder: 05 Speed
		lineageTag: 8e8b8774-2a8e-45d2-8524-ed1626a8797d

	/// Stolen bases scaled to a full season.
	measure 'SB per 162 Games' =
			DIVIDE(SUM(baseball_hits[SB]), SUM(baseball_hits[G])) * 162
		formatString: 0.0
		displayFolder: 05 Speed
		lineageTag: e1cae906-717d-4e38-96e6-0314d684e4ca

	/// Bill James basic Runs Created = (H+BB)*TB/(AB+BB).
	measure 'Runs Created (basic)' =
			DIVIDE(
			    ( SUM(baseball_hits[H]) + SUM(baseball_hits[BB]) ) * [Total Bases],
			    SUM(baseball_hits[AB]) + SUM(baseball_hits[BB])
			)
		formatString: #,0
		displayFolder: 06 Value
		lineageTag: 947a54cc-563a-44cc-8154-c94fc3b5c9da

	/// Career hits per season played.
	measure 'Hits per Season' =
			DIVIDE(SUM(baseball_hits[H]), SUM(baseball_hits[YRS]))
		formatString: 0.0
		displayFolder: 06 Value
		lineageTag: f6bce134-d36a-4b5a-87b8-27ac3292bfe7

	/// Durability proxy: games per season.
	measure 'Games per Season' =
			DIVIDE(SUM(baseball_hits[G]), SUM(baseball_hits[YRS]))
		formatString: 0.0
		displayFolder: 06 Value
		lineageTag: 69a7d979-bbd9-4b9b-80f6-b52818cf3ae1

	/// Hall of Fame players (HOF flag 1 or 2).
	measure 'HOF Count' =
			CALCULATE(DISTINCTCOUNT(baseball_hits[PLAYER]), baseball_hits[HOF] >= 1)
		formatString: #,0
		displayFolder: 07 Hall of Fame
		lineageTag: 07f09b49-8e99-4705-bc97-c398c6f110ee

	/// Non-inducted players; strict complement of HOF Count.
	measure 'Non-HOF Count' =
			CALCULATE(DISTINCTCOUNT(baseball_hits[PLAYER]), baseball_hits[HOF] = 0)
		formatString: #,0
		displayFolder: 07 Hall of Fame
		lineageTag: 4f6e6c3b-ab43-44f9-918d-01a094df9e81

	/// Share of players in context who are in the Hall of Fame.
	measure 'HOF Rate' =
			DIVIDE([HOF Count], [Total Players])
		formatString: 0.0%
		displayFolder: 07 Hall of Fame
		lineageTag: ec76d6c0-a72f-4f6c-844f-961ff1715e01

	/// Average career HR per Hall of Famer.
	measure 'HOF Avg HR' =
			CALCULATE(DIVIDE(SUM(baseball_hits[HR]), DISTINCTCOUNT(baseball_hits[PLAYER])), baseball_hits[HOF] >= 1)
		formatString: 0.0
		displayFolder: 07 Hall of Fame
		lineageTag: c2e34261-017c-4a5e-9283-7b0fa409f794

	/// Average career HR per non-inducted player.
	measure 'Non-HOF Avg HR' =
			CALCULATE(DIVIDE(SUM(baseball_hits[HR]), DISTINCTCOUNT(baseball_hits[PLAYER])), baseball_hits[HOF] = 0)
		formatString: 0.0
		displayFolder: 07 Hall of Fame
		lineageTag: 900a1e3c-e8ac-4b29-a6cf-6d84b798c7e2

	/// Aggregate batting average of Hall of Famers.
	measure 'HOF BA' =
			CALCULATE([Batting Average], baseball_hits[HOF] >= 1)
		formatString: 0.000
		displayFolder: 07 Hall of Fame
		lineageTag: 3a7c2009-d1e4-4ab7-a3cb-61b6d9a46187

	/// Aggregate batting average of non-inducted players.
	measure 'Non-HOF BA' =
			CALCULATE([Batting Average], baseball_hits[HOF] = 0)
		formatString: 0.000
		displayFolder: 07 Hall of Fame
		lineageTag: be0ce7da-c21e-4a9e-8f50-dfa5be91b25d

	/// Approx OPS of Hall of Famers.
	measure 'HOF OPS (approx)' =
			CALCULATE([OPS (approx)], baseball_hits[HOF] >= 1)
		formatString: 0.000
		displayFolder: 07 Hall of Fame
		lineageTag: 5215af0a-4475-4b89-ba5d-2aa3a03f2b11

	/// Approx OPS of non-inducted players.
	measure 'Non-HOF OPS (approx)' =
			CALCULATE([OPS (approx)], baseball_hits[HOF] = 0)
		formatString: 0.000
		displayFolder: 07 Hall of Fame
		lineageTag: 9ad4da0c-5b79-4fe6-8996-5a37545ec4b9

	/// How many times the field's average HR a Hall of Famer hits.
	measure 'HOF vs Field HR Multiple' =
			DIVIDE([HOF Avg HR], [Non-HOF Avg HR])
		formatString: 0.0"x"
		displayFolder: 07 Hall of Fame
		lineageTag: c3c9af93-014d-4ee3-b262-3736bdcb9ef6

	/// Average seasons per player.
	measure 'Avg Career Length (YRS)' =
			DIVIDE(SUM(baseball_hits[YRS]), [Total Players])
		formatString: 0.0
		displayFolder: 08 Profile & Clubs
		lineageTag: afc6a439-747a-45a5-b61a-c7ba48e9337b

	/// Average career hits per player.
	measure 'Avg Career Hits' =
			DIVIDE(SUM(baseball_hits[H]), [Total Players])
		formatString: #,0
		displayFolder: 08 Profile & Clubs
		lineageTag: f30c210f-330b-4383-8e2e-ea9d213674a9

	/// Average career HR per player.
	measure 'Avg Career HR' =
			DIVIDE(SUM(baseball_hits[HR]), [Total Players])
		formatString: 0.0
		displayFolder: 08 Profile & Clubs
		lineageTag: 8fb63401-9273-4b3f-a61f-90697f5ac5fb

	/// Players with 3,000+ career hits.
	measure '3000 Hit Club Count' =
			CALCULATE([Total Players], FILTER(VALUES(baseball_hits[PLAYER]), [Total Hits] >= 3000))
		formatString: #,0
		displayFolder: 08 Profile & Clubs
		lineageTag: 88b8b2e4-c39d-4420-b722-68cc99ffecdc

	/// Players with 500+ career home runs.
	measure '500 HR Club Count' =
			CALCULATE([Total Players], FILTER(VALUES(baseball_hits[PLAYER]), [Total Home Runs] >= 500))
		formatString: #,0
		displayFolder: 08 Profile & Clubs
		lineageTag: f3a7ef94-3a48-431d-b9f1-7828c1374cde

	/// Returns the measure chosen in the 'Rank By' field parameter (via its Order column).
	measure 'Selected Metric Value' =
			VAR sel = SELECTEDVALUE('Rank By'[Rank By Order], 0)
			RETURN
			SWITCH(
			    sel,
			    0, [Total Hits],
			    1, [Total Home Runs],
			    2, [Total RBI],
			    3, [Total Runs],
			    4, [Batting Average],
			    5, [On-Base Pct (approx)],
			    6, [Slugging Pct],
			    7, [OPS (approx)],
			    8, [Isolated Power (ISO)],
			    9, [Total Bases],
			    10, [Total Walks],
			    11, [Total Stolen Bases],
			    12, [Runs Created (basic)],
			    13, [Power-Speed Number],
			    [Total Hits]
			)
		formatStringDefinition =
				VAR sel = SELECTEDVALUE('Rank By'[Rank By Order], 0)
				RETURN
				SWITCH(
				    sel,
				    0, "#,0",
				    1, "#,0",
				    2, "#,0",
				    3, "#,0",
				    4, "0.000",
				    5, "0.000",
				    6, "0.000",
				    7, "0.000",
				    8, "0.000",
				    9, "#,0",
				    10, "#,0",
				    11, "#,0",
				    12, "#,0",
				    13, "0.0",
				    "#,0"
				)
		displayFolder: 09 Dynamic
		lineageTag: 0bb896b1-a029-4cc2-93f4-7c2e27b3d6e3

	/// Dense descending rank of the current player on the selected metric.
	measure 'Player Rank by Selected Metric' =
			IF(
			    HASONEVALUE(baseball_hits[PLAYER]),
			    RANKX(ALLSELECTED(baseball_hits[PLAYER]), [Selected Metric Value], , DESC, Dense)
			)
		formatString: #,0
		displayFolder: 09 Dynamic
		lineageTag: 8b61823b-99d7-4c33-94bb-dfadc1e7dd02

	/// Selected-metric rank expressed as a 0-100 percentile (100 = best).
	measure 'Percentile Rank by Selected Metric' =
			VAR N = COUNTROWS(ALLSELECTED(baseball_hits[PLAYER]))
			VAR Rnk = [Player Rank by Selected Metric]
			RETURN IF(NOT ISBLANK(Rnk), DIVIDE(N - Rnk, N - 1))
		formatString: 0.0%
		displayFolder: 09 Dynamic
		lineageTag: dc56290b-016f-4f30-adcd-f44c44802c51

	/// Dense rank of each player by career home runs.
	measure 'Player Rank by HR' =
			IF(
			    HASONEVALUE(baseball_hits[PLAYER]),
			    RANKX(ALLSELECTED(baseball_hits[PLAYER]), [Total Home Runs], , DESC, Dense)
			)
		formatString: #,0
		displayFolder: 09 Dynamic
		lineageTag: da6cd3b7-f57e-4181-abe9-dfd738371732

	/// Dense rank of each player by approximate OPS.
	measure 'Player Rank by OPS' =
			IF(
			    HASONEVALUE(baseball_hits[PLAYER]),
			    RANKX(ALLSELECTED(baseball_hits[PLAYER]), [OPS (approx)], , DESC, Dense)
			)
		formatString: #,0
		displayFolder: 09 Dynamic
		lineageTag: 163f7490-a9a0-410e-ad30-cc7106bed2ce

	/// Dynamic title that names the metric selected in the 'Rank By' field parameter.
	measure 'Leaderboard Title' =
			"TOP HITTERS BY " & UPPER(SELECTEDVALUE('Rank By'[Rank By], "HITS"))
		formatString: 
		displayFolder: 09 Dynamic
		lineageTag: 24385586-8405-45d1-ad2c-c5af9b8ce74b

	/// The player currently in context (for dynamic titles on the profile page).
	measure 'Selected Player' =
			SELECTEDVALUE(baseball_hits[PLAYER], "All Players")
		formatString: 
		displayFolder: 09 Dynamic
		lineageTag: cec38104-3a8c-430d-a5ea-55c9f364f968

	/// One-line dynamic career summary for the selected player.
	measure 'Player Narrative' =
			VAR p = SELECTEDVALUE(baseball_hits[PLAYER])
			RETURN
			IF(
			    HASONEVALUE(baseball_hits[PLAYER]),
			    p & " played " & [Total Seasons] & " seasons, collecting "
			        & FORMAT([Total Hits], "#,0") & " hits, " & FORMAT([Total Home Runs], "#,0")
			        & " home runs and " & FORMAT([Total RBI], "#,0") & " RBI — batting "
			        & FORMAT([Batting Average], "0.000") & " with a " & FORMAT([OPS (approx)], "0.000") & " OPS.",
			    "Select a player to see their career line."
			)
		formatString: 
		displayFolder: 09 Dynamic
		lineageTag: daea37c2-fe88-4a38-9652-97a637d5f5c5

	/// Dynamic headline for the Hall of Fame page.
	measure 'HOF Headline' =
			"HALL OF FAMERS HIT " & FORMAT([HOF vs Field HR Multiple], "0.0") & "x THE HOME RUNS OF THE FIELD"
		formatString: 
		displayFolder: 09 Dynamic
		lineageTag: 76ca2a39-5f73-4a07-b46c-838ae348d1e7

	partition _Measures = calculated
		mode: import
		source = {1}
