table _Measures
	lineageTag: da9d64ee-eac5-4fbc-9bad-28b3532477c4

	column Value
		isHidden
		lineageTag: d91fd075-67f1-4393-920d-b168581e271b
		isNameInferred
		sourceColumn: [Value]

	/// Career games played (additive).
	measure 'Total Games' =
			SUM(baseball_hits[G])
		formatString: #,0
		displayFolder: 01 Counting
		lineageTag: 6b6178ec-7d69-4ee3-8aa6-833b312628f5

	/// At-bats — the denominator for most rate stats.
	measure 'Total At-Bats' =
			SUM(baseball_hits[AB])
		formatString: #,0
		displayFolder: 01 Counting
		lineageTag: 75212418-1bdd-4b27-a165-2789fbae8b12

	/// Runs scored.
	measure 'Total Runs' =
			SUM(baseball_hits[R])
		formatString: #,0
		displayFolder: 01 Counting
		lineageTag: 280fa1f8-04a7-4831-a59e-2236c041bd8c

	/// Career hits.
	measure 'Total Hits' =
			SUM(baseball_hits[H])
		formatString: #,0
		displayFolder: 01 Counting
		lineageTag: 38efd668-d37e-434c-9ca2-a1e0b0cbbf37

	/// Doubles.
	measure 'Total Doubles' =
			SUM(baseball_hits[2B])
		formatString: #,0
		displayFolder: 01 Counting
		lineageTag: 43e6a30f-ea03-47de-a89c-2063f06dccb3

	/// Triples.
	measure 'Total Triples' =
			SUM(baseball_hits[3B])
		formatString: #,0
		displayFolder: 01 Counting
		lineageTag: c45830df-b9c9-4ef1-99c6-451ce8760ede

	/// Home runs.
	measure 'Total Home Runs' =
			SUM(baseball_hits[HR])
		formatString: #,0
		displayFolder: 01 Counting
		lineageTag: 6dd4084e-3585-47a4-b548-3b5bf285f6cb

	/// Runs batted in.
	measure 'Total RBI' =
			SUM(baseball_hits[RBI])
		formatString: #,0
		displayFolder: 01 Counting
		lineageTag: 0b393283-57a7-41c8-8fe0-fc56eaa24db7

	/// Bases on balls (walks).
	measure 'Total Walks' =
			SUM(baseball_hits[BB])
		formatString: #,0
		displayFolder: 01 Counting
		lineageTag: 82d56a74-70d8-47df-8174-ab47c928df8a

	/// Strikeouts.
	measure 'Total Strikeouts' =
			SUM(baseball_hits[SO])
		formatString: #,0
		displayFolder: 01 Counting
		lineageTag: b8ec1ead-521a-468e-968a-0168f5f19f02

	/// Stolen bases.
	measure 'Total Stolen Bases' =
			SUM(baseball_hits[SB])
		formatString: #,0
		displayFolder: 01 Counting
		lineageTag: 1eb0656f-8638-4dac-a3d3-3fb008ccbcb5

	/// Times caught stealing.
	measure 'Total Caught Stealing' =
			SUM(baseball_hits[CS])
		formatString: #,0
		displayFolder: 01 Counting
		lineageTag: 0c581d15-f6cd-48ea-8fdf-21901851fc91

	/// Seasons played (player-seasons across a group).
	measure 'Total Seasons' =
			SUM(baseball_hits[YRS])
		formatString: #,0
		displayFolder: 01 Counting
		lineageTag: ddb11b79-8d90-4003-8459-b74a307da641

	/// Distinct players in context.
	measure 'Total Players' =
			DISTINCTCOUNT(baseball_hits[PLAYER])
		formatString: #,0
		displayFolder: 01 Counting
		lineageTag: ed557185-2c84-4018-8cff-891b9f99778f

	/// Approx plate appearances = AB + BB (no HBP/SF/SH in source).
	measure 'Total Plate Appearances' =
			SUM(baseball_hits[AB]) + SUM(baseball_hits[BB])
		formatString: #,0
		displayFolder: 01 Counting
		lineageTag: 8b070f82-799d-47b5-b413-4d2924549640

	/// Hits / at-bats, aggregated SUM/SUM so it is correct at any grain.
	measure 'Batting Average' =
			DIVIDE(SUM(baseball_hits[H]), SUM(baseball_hits[AB]))
		formatString: 0.000
		displayFolder: 02 Rate Stats
		lineageTag: 99837fb1-9643-4688-972a-aa2f456c6fde

	/// Approx OBP = (H+BB)/(AB+BB). No HBP/SF in source, so slightly below official OBP.
	measure 'On-Base Pct (approx)' =
			DIVIDE(SUM(baseball_hits[H]) + SUM(baseball_hits[BB]), SUM(baseball_hits[AB]) + SUM(baseball_hits[BB]))
		formatString: 0.000
		displayFolder: 02 Rate Stats
		lineageTag: cf8beff0-1426-4ceb-b571-899f0d413406

	/// Total bases / at-bats; singles derived as H-2B-3B-HR.
	measure 'Slugging Pct' =
			DIVIDE(
			    ( SUM(baseball_hits[H]) - SUM(baseball_hits[2B]) - SUM(baseball_hits[3B]) - SUM(baseball_hits[HR]) )
			        + 2 * SUM(baseball_hits[2B]) + 3 * SUM(baseball_hits[3B]) + 4 * SUM(baseball_hits[HR]),
			    SUM(baseball_hits[AB])
			)
		formatString: 0.000
		displayFolder: 02 Rate Stats
		lineageTag: 82e50b6d-3ed9-4d9d-bad3-4a7b2b51d43f

	/// On-base plus slugging. Inherits the OBP approximation.
	measure 'OPS (approx)' =
			[On-Base Pct (approx)] + [Slugging Pct]
		formatString: 0.000
		displayFolder: 02 Rate Stats
		lineageTag: 9952f59d-bcea-44e9-9768-3323c2e45e72

	/// Extra-base productivity = SLG - BA on aggregates.
	measure 'Isolated Power (ISO)' =
			[Slugging Pct] - [Batting Average]
		formatString: 0.000
		displayFolder: 02 Rate Stats
		lineageTag: 062b31f7-ddc0-4de4-bac1-5536d7d96d83

	/// 1B + 2*2B + 3*3B + 4*HR.
	measure 'Total Bases' =
			( SUM(baseball_hits[H]) - SUM(baseball_hits[2B]) - SUM(baseball_hits[3B]) - SUM(baseball_hits[HR]) )
			    + 2 * SUM(baseball_hits[2B]) + 3 * SUM(baseball_hits[3B]) + 4 * SUM(baseball_hits[HR])
		formatString: #,0
		displayFolder: 03 Power
		lineageTag: 063a5f8a-e04e-4345-8137-c9b584ce9663

	/// Hits minus extra-base hits.
	measure 'Singles' =
			SUM(baseball_hits[H]) - SUM(baseball_hits[2B]) - SUM(baseball_hits[3B]) - SUM(baseball_hits[HR])
		formatString: #,0
		displayFolder: 03 Power
		lineageTag: 27a6ae71-4c73-40ec-8a60-93a206cc20fe

	/// Doubles + triples + home runs.
	measure 'Extra-Base Hits' =
			SUM(baseball_hits[2B]) + SUM(baseball_hits[3B]) + SUM(baseball_hits[HR])
		formatString: #,0
		displayFolder: 03 Power
		lineageTag: 6ac38334-76a0-403e-8522-5c043b0deb80

	/// At-bats per home run; lower = more power.
	measure 'AB per HR' =
			DIVIDE(SUM(baseball_hits[AB]), SUM(baseball_hits[HR]))
		formatString: 0.0
		displayFolder: 03 Power
		lineageTag: 22097b43-521a-4bb7-98e6-c5f9f96b2cd6

	/// Home-run rate scaled to a full season.
	measure 'HR per 162 Games' =
			DIVIDE(SUM(baseball_hits[HR]), SUM(baseball_hits[G])) * 162
		formatString: 0.0
		displayFolder: 03 Power
		lineageTag: e475a516-3c47-49e2-a65c-1f1c292d9e9c

	/// Share of hits going for extra bases.
	measure 'XBH Pct of Hits' =
			DIVIDE([Extra-Base Hits], SUM(baseball_hits[H]))
		formatString: 0.0%
		displayFolder: 03 Power
		lineageTag: f59c990f-83e9-414f-801f-801e83ceeb1a

	/// Share of hits that are home runs.
	measure 'HR Pct of Hits' =
			DIVIDE(SUM(baseball_hits[HR]), SUM(baseball_hits[H]))
		formatString: 0.0%
		displayFolder: 03 Power
		lineageTag: 4e14127a-d60b-4041-8b0b-38e483b781a1

	/// Walk-to-strikeout ratio; higher = better plate discipline.
	measure 'BB per K' =
			DIVIDE(SUM(baseball_hits[BB]), SUM(baseball_hits[SO]))
		formatString: 0.00
		displayFolder: 04 Discipline
		lineageTag: 6d59acf0-fe72-4987-a9af-dd2f56422521

	/// Strikeouts per approx plate appearance.
	measure 'Strikeout Pct (approx)' =
			DIVIDE(SUM(baseball_hits[SO]), SUM(baseball_hits[AB]) + SUM(baseball_hits[BB]))
		formatString: 0.0%
		displayFolder: 04 Discipline
		lineageTag: bc403a06-d686-40e8-aabb-473a2740c8d2

	/// Walks per approx plate appearance.
	measure 'Walk Pct (approx)' =
			DIVIDE(SUM(baseball_hits[BB]), SUM(baseball_hits[AB]) + SUM(baseball_hits[BB]))
		formatString: 0.0%
		displayFolder: 04 Discipline
		lineageTag: 15420466-423f-4ad5-9bc1-9b000b00607d

	/// Stolen-base success = SB / (SB + CS).
	measure 'SB Success Pct' =
			DIVIDE(SUM(baseball_hits[SB]), SUM(baseball_hits[SB]) + SUM(baseball_hits[CS]))
		formatString: 0.0%
		displayFolder: 05 Speed
		lineageTag: af3d6a72-3f2a-4b6b-a066-3daed09d4fbc

	/// Total SB attempts.
	measure 'Stolen Base Attempts' =
			SUM(baseball_hits[SB]) + SUM(baseball_hits[CS])
		formatString: #,0
		displayFolder: 05 Speed
		lineageTag: 95cdaedf-49c6-41ba-8b7e-decf348e2f0e

	/// Bill James Power-Speed Number = (2*HR*SB)/(HR+SB).
	measure 'Power-Speed Number' =
			VAR HRs = SUM(baseball_hits[HR])
			VAR SBs = SUM(baseball_hits[SB])
			RETURN DIVIDE(2 * HRs * SBs, HRs + SBs)
		formatString: 0.0
		displayFolder: 05 Speed
		lineageTag: df485587-5069-4dd5-9f9d-54cee5c0bf5c

	/// Stolen bases scaled to a full season.
	measure 'SB per 162 Games' =
			DIVIDE(SUM(baseball_hits[SB]), SUM(baseball_hits[G])) * 162
		formatString: 0.0
		displayFolder: 05 Speed
		lineageTag: 5552bf8d-d375-484b-aed3-8499b181d121

	/// Bill James basic Runs Created = (H+BB)*TB/(AB+BB).
	measure 'Runs Created (basic)' =
			DIVIDE(
			    ( SUM(baseball_hits[H]) + SUM(baseball_hits[BB]) ) * [Total Bases],
			    SUM(baseball_hits[AB]) + SUM(baseball_hits[BB])
			)
		formatString: #,0
		displayFolder: 06 Value
		lineageTag: 13dc390b-15a7-451f-b21a-62685a6ed359

	/// Career hits per season played.
	measure 'Hits per Season' =
			DIVIDE(SUM(baseball_hits[H]), SUM(baseball_hits[YRS]))
		formatString: 0.0
		displayFolder: 06 Value
		lineageTag: 7af72eb8-0884-42e0-84e8-77930c7f2b92

	/// Durability proxy: games per season.
	measure 'Games per Season' =
			DIVIDE(SUM(baseball_hits[G]), SUM(baseball_hits[YRS]))
		formatString: 0.0
		displayFolder: 06 Value
		lineageTag: 4ca42bf5-b56a-4af9-9642-6e6bf7331981

	/// Hall of Fame players (HOF flag 1 or 2).
	measure 'HOF Count' =
			CALCULATE(DISTINCTCOUNT(baseball_hits[PLAYER]), baseball_hits[HOF] >= 1)
		formatString: #,0
		displayFolder: 07 Hall of Fame
		lineageTag: 994fd249-532e-49aa-9309-0d0185c22bba

	/// Non-inducted players; strict complement of HOF Count.
	measure 'Non-HOF Count' =
			CALCULATE(DISTINCTCOUNT(baseball_hits[PLAYER]), baseball_hits[HOF] = 0)
		formatString: #,0
		displayFolder: 07 Hall of Fame
		lineageTag: 0fe6dc66-d3e4-4975-949e-f9a8fafa54a5

	/// Share of players in context who are in the Hall of Fame.
	measure 'HOF Rate' =
			DIVIDE([HOF Count], [Total Players])
		formatString: 0.0%
		displayFolder: 07 Hall of Fame
		lineageTag: 4c4b5d0c-cc0d-4bde-a0d7-df2e3e9d2855

	/// Average career HR per Hall of Famer.
	measure 'HOF Avg HR' =
			CALCULATE(DIVIDE(SUM(baseball_hits[HR]), DISTINCTCOUNT(baseball_hits[PLAYER])), baseball_hits[HOF] >= 1)
		formatString: 0.0
		displayFolder: 07 Hall of Fame
		lineageTag: ae2cb343-15ee-4b3d-af80-25f8ac60d91a

	/// Average career HR per non-inducted player.
	measure 'Non-HOF Avg HR' =
			CALCULATE(DIVIDE(SUM(baseball_hits[HR]), DISTINCTCOUNT(baseball_hits[PLAYER])), baseball_hits[HOF] = 0)
		formatString: 0.0
		displayFolder: 07 Hall of Fame
		lineageTag: e2edf3a2-3b19-4c83-bfc6-9490ec9a6b2d

	/// Aggregate batting average of Hall of Famers.
	measure 'HOF BA' =
			CALCULATE([Batting Average], baseball_hits[HOF] >= 1)
		formatString: 0.000
		displayFolder: 07 Hall of Fame
		lineageTag: a7932e7e-9a50-4773-abb6-82c1294fdb64

	/// Aggregate batting average of non-inducted players.
	measure 'Non-HOF BA' =
			CALCULATE([Batting Average], baseball_hits[HOF] = 0)
		formatString: 0.000
		displayFolder: 07 Hall of Fame
		lineageTag: 791244df-8aba-457a-af46-05cdc1a4568e

	/// Approx OPS of Hall of Famers.
	measure 'HOF OPS (approx)' =
			CALCULATE([OPS (approx)], baseball_hits[HOF] >= 1)
		formatString: 0.000
		displayFolder: 07 Hall of Fame
		lineageTag: 7ef3305d-09dc-431d-82df-be130144f7ba

	/// Approx OPS of non-inducted players.
	measure 'Non-HOF OPS (approx)' =
			CALCULATE([OPS (approx)], baseball_hits[HOF] = 0)
		formatString: 0.000
		displayFolder: 07 Hall of Fame
		lineageTag: 56950b54-1b9f-436d-9c1a-13afaa87cc56

	/// How many times the field's average HR a Hall of Famer hits.
	measure 'HOF vs Field HR Multiple' =
			DIVIDE([HOF Avg HR], [Non-HOF Avg HR])
		formatString: 0.0"x"
		displayFolder: 07 Hall of Fame
		lineageTag: 56a3efb4-d7a5-4df3-ad6d-6d05892251f4

	/// Average seasons per player.
	measure 'Avg Career Length (YRS)' =
			DIVIDE(SUM(baseball_hits[YRS]), [Total Players])
		formatString: 0.0
		displayFolder: 08 Profile & Clubs
		lineageTag: 60dbda1d-fc89-4982-ac94-a7b35ff2a8bb

	/// Average career hits per player.
	measure 'Avg Career Hits' =
			DIVIDE(SUM(baseball_hits[H]), [Total Players])
		formatString: #,0
		displayFolder: 08 Profile & Clubs
		lineageTag: 013033e9-e33e-4c74-b827-9076171c2092

	/// Average career HR per player.
	measure 'Avg Career HR' =
			DIVIDE(SUM(baseball_hits[HR]), [Total Players])
		formatString: 0.0
		displayFolder: 08 Profile & Clubs
		lineageTag: 11060131-2d72-4c54-ada2-d81c784069ce

	/// Players with 3,000+ career hits.
	measure '3000 Hit Club Count' =
			CALCULATE([Total Players], FILTER(VALUES(baseball_hits[PLAYER]), [Total Hits] >= 3000))
		formatString: #,0
		displayFolder: 08 Profile & Clubs
		lineageTag: 4773793d-4caa-4341-9356-d6128311ba15

	/// Players with 500+ career home runs.
	measure '500 HR Club Count' =
			CALCULATE([Total Players], FILTER(VALUES(baseball_hits[PLAYER]), [Total Home Runs] >= 500))
		formatString: #,0
		displayFolder: 08 Profile & Clubs
		lineageTag: 84025b67-c596-41b9-b6c8-7a9905704f0b

	/// Returns the measure chosen in the 'Rank By' field parameter (via its Order column). Format #,0.### shows whole counts and 3-decimal rates alike.
	measure 'Selected Metric Value' =
			VAR sel = SELECTEDVALUE('Rank By'[Rank By Order], 0)
			RETURN
			SWITCH(
			    sel,
			    0, [Total Hits],
			    1, [Total Home Runs],
			    2, [Total RBI],
			    3, [Total Runs],
			    4, [Batting Average],
			    5, [On-Base Pct (approx)],
			    6, [Slugging Pct],
			    7, [OPS (approx)],
			    8, [Isolated Power (ISO)],
			    9, [Total Bases],
			    10, [Total Walks],
			    11, [Total Stolen Bases],
			    12, [Runs Created (basic)],
			    13, [Power-Speed Number],
			    [Total Hits]
			)
		formatString: #,0.###
		displayFolder: 09 Dynamic
		lineageTag: 9447436d-9515-4da8-886d-26e3537fd8e1

	/// Dense descending rank of the current player on the selected metric.
	measure 'Player Rank by Selected Metric' =
			IF(
			    HASONEVALUE(baseball_hits[PLAYER]),
			    RANKX(ALLSELECTED(baseball_hits[PLAYER]), [Selected Metric Value], , DESC, Dense)
			)
		formatString: #,0
		displayFolder: 09 Dynamic
		lineageTag: 6ffac2ac-bd05-459f-9362-33c74704710a

	/// Selected-metric rank expressed as a 0-100 percentile (100 = best).
	measure 'Percentile Rank by Selected Metric' =
			VAR N = COUNTROWS(ALLSELECTED(baseball_hits[PLAYER]))
			VAR Rnk = [Player Rank by Selected Metric]
			RETURN IF(NOT ISBLANK(Rnk), DIVIDE(N - Rnk, N - 1))
		formatString: 0.0%
		displayFolder: 09 Dynamic
		lineageTag: 867d74b9-6679-4d9c-8ccd-72b9ed75463c

	/// Dense rank of each player by career home runs.
	measure 'Player Rank by HR' =
			IF(
			    HASONEVALUE(baseball_hits[PLAYER]),
			    RANKX(ALLSELECTED(baseball_hits[PLAYER]), [Total Home Runs], , DESC, Dense)
			)
		formatString: #,0
		displayFolder: 09 Dynamic
		lineageTag: 83148db9-34df-4117-9be0-153d97467670

	/// Dense rank of each player by approximate OPS.
	measure 'Player Rank by OPS' =
			IF(
			    HASONEVALUE(baseball_hits[PLAYER]),
			    RANKX(ALLSELECTED(baseball_hits[PLAYER]), [OPS (approx)], , DESC, Dense)
			)
		formatString: #,0
		displayFolder: 09 Dynamic
		lineageTag: 6bcafe16-55bd-4077-9775-556a64e19153

	/// Dynamic title that names the metric selected in the 'Rank By' field parameter.
	measure 'Leaderboard Title' =
			"TOP HITTERS BY " & UPPER(SELECTEDVALUE('Rank By'[Rank By], "HITS"))
		displayFolder: 09 Dynamic
		lineageTag: e4de73e7-6f38-48d9-803e-787bd934c051

	/// The player currently in context (for dynamic titles on the profile page).
	measure 'Selected Player' =
			SELECTEDVALUE(baseball_hits[PLAYER], "All Players")
		displayFolder: 09 Dynamic
		lineageTag: 6909b2be-52fe-4dda-857c-4e193ddf2540

	/// One-line dynamic career summary for the selected player.
	measure 'Player Narrative' =
			VAR p = SELECTEDVALUE(baseball_hits[PLAYER])
			RETURN
			IF(
			    HASONEVALUE(baseball_hits[PLAYER]),
			    p & " played " & [Total Seasons] & " seasons, collecting "
			        & FORMAT([Total Hits], "#,0") & " hits, " & FORMAT([Total Home Runs], "#,0")
			        & " home runs and " & FORMAT([Total RBI], "#,0") & " RBI — batting "
			        & FORMAT([Batting Average], "0.000") & " with a " & FORMAT([OPS (approx)], "0.000") & " OPS.",
			    "Select a player to see their career line."
			)
		displayFolder: 09 Dynamic
		lineageTag: 92f05281-bb2e-423d-9617-09f71c678c1a

	/// Dynamic headline for the Hall of Fame page.
	measure 'HOF Headline' =
			"HALL OF FAMERS HIT " & FORMAT([HOF vs Field HR Multiple], "0.0") & "x THE HOME RUNS OF THE FIELD"
		displayFolder: 09 Dynamic
		lineageTag: 039619a5-9d07-4e15-846e-d1d136738a7d

	partition _Measures = calculated
		mode: import
		source = {1}
